backend:
  name: git-gateway
  repo: senegalx/theodore-monteil
  branch: master

publish_mode: editorial_workflow
logo_url: https://theodore-monteil.netlify.app/images/site-navigation/logo-login.png
locale: 'fr'
media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "home"
    label: "Accueil"
    files:
      - file: "site/data/hero.yml"
        label: "Hero"
        name: "hero"
        fields:
          - {label: "Afficher", name: "enable", widget: "boolean", default: true}
          - {label: Titre, name: topTitle, widget: string}
          - {label: "Texte", name: "content", widget: 'markdown' }
          - {label: "Nom Bouton", name: buttonName, widget: string}
          - {label: "Lien Bouton", name: buttonURL, widget: string}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Vidéo Image", name: "videoThumb", widget: "image", required: false}
          - {label: "Lien Vidéo", name: videoURL, widget: string}
      - file: "site/data/aboutSection.yml"
        label: "À propos"
        name: "about"
        fields:
          - {label: "Afficher", name: "enable", widget: "boolean", default: true}
          - {label: Titre haut, name: topTitle, widget: string}
          - {label: "Titre", name: "title", widget: 'markdown' }
          - {label: "Texte", name: "content", widget: 'markdown' }
          - {label: "Nom Bouton 1", name: button1Name, widget: string}
          - {label: "Nom Bouton 2", name: button2Name, widget: string}
          - {label: "Lien Bouton 1", name: button1Target, widget: string}
          - {label: "Lien Bouton 2", name: button2Target, widget: string}
          - {label: "Image", name: "image", widget: "image", required: false}
      - file: "site/data/serviceSection.yml"
        label: "Programmes"
        name: "program"
        fields:
          - {label: "Afficher", name: "enable", widget: "boolean", default: true}
          - {label: Titre haut, name: topTitle, widget: string}
          - {label: "Titre", name: "title", widget: 'markdown' }
          - label: "Programme"
            name: "service"
            collapsed: true
            widget: "list"
            fields:
              - {label: "Texte", name: "content", widget: 'markdown' }
              - {label: "Image", name: "image", widget: "image", required: false}
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image Aperçus", name: "featureImage", widget: "image", required: false}
      - {label: "Image", name: "postImage", widget: "image", required: false}
      - {label: "Corps", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Gouvernance"
    folder: "site/content/portfolio"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Service", name: "service", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Description", name: "shortDescription", widget: "text"}
      - {label: "Challenge", name: "challenge", widget: "text"}
      - {label: "solution", name: "solution", widget: "text"}
      - {label: "Corps", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/contact/_index.md"
        label: "Page Contact"
        name: "contact"
        fields:
          - {label: Titre, name: title, widget: string}
          - {label: Menu, name: breadcrumb, widget: string}